### POST SIGNUP AUTHENTICATION /authentication/signup ###
POST http://localhost:3000/authentication/signup
X-Request-ID: 123
X-Client-ID: 123
Content-Type: application/json

{
    "username": "willtodd03@gmail.com",
    "password": "Test_123"
}

### PUT LOGIN AUTHENTICATION /authentication/login ###
PUT http://localhost:3000/authentication/login
X-Request-ID: 123
X-Client-ID: 123
Content-Type: application/json

{
    "username": "willtodd03@gmail.com",
    "password": "Test_123"
}