### POST SIGNUP AUTHENTICATION /authentication/signup ###
POST http://localhost:3000/authentication/signup
X-Request-ID: 123
X-Client-ID: 123
Content-Type: application/json

{
    "username": "willtodd03@gmail.com",
    "password": "Test_123"
}

### POST SIGNUP AUTHENTICATION IN DOCKER CONTAINER /authentication/signup ###
POST http://localhost/authentication/signup
X-Request-ID: 123
X-Client-ID: 123
Content-Type: application/json

{
    "username": "willtodd03@gmail.com",
    "password": "Test_123"
}